# Generated by Django 3.0.5 on 2021-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer_thing', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='image1',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='image2',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='image3',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='image4',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='image5',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
