# Generated by Django 3.0.5 on 2021-11-15 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photographer_thing', '0004_auto_20211114_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
