# Generated by Django 3.0.5 on 2021-11-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211112_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='near_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
