# Generated by Django 3.0.5 on 2021-11-12 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20211112_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
