# Generated by Django 3.0.5 on 2021-11-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer_thing', '0005_auto_20211115_2059'),
        ('customer', '0007_auto_20211117_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='photographer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_detaila', to='photographer_thing.photographer'),
        ),
    ]
