# Generated by Django 3.0.5 on 2021-11-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20211117_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='photographer',
            new_name='photographe_id',
        ),
    ]
