# Generated by Django 3.0.5 on 2021-11-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20211117_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='photographe_id',
            new_name='photographer',
        ),
    ]
