# Generated by Django 3.0.5 on 2021-12-03 14:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer_thing', '0005_auto_20211115_2059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0011_auto_20211117_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('near_by', models.CharField(max_length=100, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('photographer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_set', to='photographer_thing.photographer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
