# Generated by Django 3.0.5 on 2021-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
