# Generated by Django 3.0.5 on 2021-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='user',
        ),
        migrations.AddField(
            model_name='photographer',
            name='awards',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='company_colaboration',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='preffred_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
