# Generated by Django 3.0.5 on 2021-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210915_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
