# Generated by Django 3.0.5 on 2021-09-08 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210908_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='user',
            field=models.OneToOneField(default='photographer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
