# Generated by Django 3.0.5 on 2021-09-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210916_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photographer',
        ),
    ]
