# Generated by Django 3.0.5 on 2021-09-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210909_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='user',
        ),
    ]
