# Generated by Django 3.0.5 on 2021-11-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('customer', 'Customer')], max_length=20),
        ),
    ]
