# Generated by Django 3.0.5 on 2021-09-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_photographer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
