# Generated by Django 3.2.6 on 2022-01-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_dest_contact', '0002_auto_20210906_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
