# Generated by Django 3.2.6 on 2021-08-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_dest_contact', '0002_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='image',
            new_name='tumbnail',
        ),
        migrations.AddField(
            model_name='destination',
            name='popular_for',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
