# Generated by Django 3.2.6 on 2021-08-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_dest_contact', '0003_auto_20210823_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='pic1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='pic2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='pic3',
            field=models.URLField(null=True),
        ),
    ]
