# Generated by Django 3.2.6 on 2021-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_dest_contact', '0004_auto_20210823_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='pic1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='pic2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='pic3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
