# Generated by Django 3.0.5 on 2021-08-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_dest_contact', '0005_auto_20210823_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
